# Copyright (C) 2018 The LineageOS Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/google/clockwork/setup-makefiles.sh

PRODUCT_COPY_FILES += \
    vendor/google/clockwork/proprietary/bin/ClockworkProxy:system/bin/ClockworkProxy \
    vendor/google/clockwork/proprietary/etc/permissions/clockwork-system.xml:system/etc/permissions/clockwork-system.xml \
    vendor/google/clockwork/proprietary/etc/permissions/clockwork.xml:system/etc/permissions/clockwork.xml \
    vendor/google/clockwork/proprietary/etc/permissions/com.google.android.wearable.xml:system/etc/permissions/com.google.android.wearable.xml \
    vendor/google/clockwork/proprietary/etc/permissions/com.google.wearable.hardware.sensor.heartrate.fitness.xml:system/etc/permissions/com.google.wearable.hardware.sensor.heartrate.fitness.xml \
    vendor/google/clockwork/proprietary/etc/permissions/privapp-permissions-clockwork.xml:system/etc/permissions/privapp-permissions-clockwork.xml \
    vendor/google/clockwork/proprietary/etc/permissions/watch_features.xml:system/etc/permissions/watch_features.xml \
    vendor/google/clockwork/proprietary/etc/preloaded-classes:system/etc/preloaded-classes \
    vendor/google/clockwork/proprietary/framework/clockwork-system.jar:system/framework/clockwork-system.jar \
    vendor/google/clockwork/proprietary/framework/com.google.android.wearable.jar:system/framework/com.google.android.wearable.jar \
    vendor/google/clockwork/proprietary/framework/wear-service.jar:system/framework/wear-service.jar \
    vendor/google/clockwork/proprietary/lib/libclockwork-bluetooth-jni.so:system/lib/libclockwork-bluetooth-jni.so \
    vendor/google/clockwork/proprietary/lib/libclockwork_proxy_jni.so:system/lib/libclockwork_proxy_jni.so \
    vendor/google/clockwork/proprietary/lib/libwear-bluetooth-jni.so:system/lib/libwear-bluetooth-jni.so

PRODUCT_PACKAGES += \
    ClockworkFlashlight \
    ClockworkFrameworkPackageStubs \
    GoogleContactsSyncAdapter \
    GoogleExtShared \
    PrebuiltDeskClockMicroApp \
    RemindersPrebuiltWearable \
    TalkbackWearPrebuilt \
    TranslatePrebuiltWearable \
    WearHandwriting \
    WearKeyboard \
    ClockworkAmbient \
    ClockworkBluetooth \
    libwear-bluetooth-jni \
    ClockworkBugReportSender \
    ClockworkHomeGoogle \
    ClockworkPhone \
    ClockworkRetailAttractLoop \
    ClockworkSearch \
    ClockworkSettings \
    ClockworkSetupWizard \
    ClockworkSystemUI \
    FitnessPrebuiltWearable \
    GoogleExtServices \
    GooglePackageInstaller \
    GoogleServicesFramework \
    PrebuiltGmsCoreForClockworkWearable \
    PrebuiltGmsCoreForClockwork_WearableSidecar \
    PrebuiltWearsky \
    WristGesturesTutorial
